# Generated by Django 4.0.4 on 2022-08-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('profile_pic', models.ImageField(null=True, upload_to='profilepics')),
                ('emp_name', models.CharField(max_length=120)),
                ('desig', models.CharField(max_length=120)),
                ('salary', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('experience', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
