# Generated by Django 4.0.4 on 2022-08-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_employee_delete_blogs_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='desig',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
